import cv2

def get_bounding_box(mask):
    mask_uint8 = (mask * 255).astype(np.uint8)

    # There might be some other artifacts detected in this mask, to cope with that we find all the contours in the mask 
    contours, _ = cv2.findContours(mask_uint8, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return None

    # And then we select the bigger one
    sorted_contours = sorted(contours, key=cv2.contourArea, reverse=True)
    x, y, w, h = cv2.boundingRect(sorted_contours[0])  # you can also loop through all if needed
    return x, y, w, h


def detour_box(image, masks):
    
    # Sort the masks by their area
    masks_sorted = sorted(masks, key=lambda k: k['area'], reverse=True)

    # The object corresponding to the box should be the 2nd one (idx 1)
    box = masks_sorted[1]
    mask_box = box['segmentation']    

    # Filter the points according to the mask
    # We need to add one dimension to the mask generated by SAM2 in order to cop with the fact that an image is (height * width * 3)
    m = np.transpose(np.array([mask_box for i in range(image.shape[2])]), (1, 2, 0))
    box_img_filt = image * m

    # Detour the box
    x, y, w, h = get_bounding_box(mask_box)
    x, y, w, h = int(x), int(y), int(w), int(h)
    box_img = box_img_filt[y:y+h, x:x+w]

    return box_img


masks = mask_generator.generate(image)
box_img = detour_box(image, masks)

fig = plt.figure(figsize=(6, 6))
plt.title("Image détourée")
plt.imshow(box_img)
plt.show()